
import java.util.*;

/* If we compare two objects of a same non primitive class we are going to get false becuasse by defualt the 
    == operator comapres only the memory of thetwo objjects. It doesnt compare if the values of the attributes 
    of the two objects is same hence they are equal. 
    
    Eg: if we have two student objects they will be equal if all of theier object variables values is same 

    We ccan do this comparision only if we have overriden the equlas method in the custom class that we 
    created. this equals method is present in the super class of all classes tht Object class.

    This .equals() method is what is overriden by the string class to compare two strings together to see if they are same or not. 
    We use this same strategy to see if two instances of same classes is same or not by comparing their 
    corresponding object variables and apssing the verdict if they aare equal or not.

    But even if we still override the .equals() method. THd hash code generated by the objects is going to 
    be different since they are two different instances. to solve this we will make use of the hashCode
    method in the Object class to create our own implementation of the hashCode method by overiding it 
    based on the variables of our custom class. 

    By doing so we will get same value for the same objects that have same object variable values. 

    Why we do this?
    to store them inside a hashset or retrieve their value from a hashmap

    HashSet only allows unique values. if they are prmitive data types we will have their values comapred 
    And any eentry with dupplicate values will be rejected and will counted as one. 

    So what if we are storing custom objects then the comparision is done using the hashCode generated 
    by the objects. But that is only if we have overriden the hashCode method in our custom class. If not 
    we would be able to store the different objects of the same class who have the same object variable 
    value. 

    We could also retrive the values of this objeccts if we store them in a hash map when we try to 
    use .get() method in on HashMap it will hash the value and then we will be returned the corresponding 
    value of that key. If we have not overridden the hasshCode method in our custom class we would not 
    get the value as it is treated as a different object.

*/


class jaffer{
    public static void main(String[] args){
        A a= new A(10);
        // A aCopy= a;
        // System.out.println(a.hashCode());   
        // System.out.println(aCopy.hashCode());  
        
        A a2= new A(10);
        // System.out.println(a2.hashCode());
        
        A a3= new A(20);

        A a4= new A(30);
            
        // System.out.println(a.equals(aCopy)?"true":"false");
        // System.out.println(a.equals(a2)?"true":"false");
        // System.out.println(a.equals(a3)?"true":"false");
        
        // Set<A> hs= new HashSet<>();

        // hs.add(a);
        // hs.add(aCopy);
        // hs.add(a2);
        // hs.add(a3);
        // hs.add(a4);

        // System.out.println(hs.size());


        Map<A, Integer> hm= new HashMap<>();

        hm.put(a3, 2);
        hm.put(a4, 3);
        hm.put(a2, 100);

        System.out.println(hm.get(a));
    }
}

class A{
    int id;

    public A(int id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object a){
        if (!(a instanceof A)){
            return false;
        }

        if (this== a) {
            return true;
        }
           
        A b= (A) a;

        return b.id== this.id;

    }

    @Override
     public int hashCode() {
        return Objects.hash(this.id);  
    }
}
